import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "./style.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{backgroundColor:"#213885",
      padding:"3rem", }}>
<h1>MCB BANK </h1>
      </header>{children}<footer style={{
          backgroundColor:"#2caf20",
          padding: "3rem",
        }}> All rights reserved</footer>
        </body>
    </html>
  )
}
